export type GameLanguage = 'en' | 'pt' | 'ko';

const defaultLanguage: GameLanguage = 'ko';
const languageStorageKey = 'farming-simulator-cabacos-language';

const translations = {
    en: {
        cropMarketTitle: 'Crop Market',
        sell: 'Sell',
        sold: 'Sold',
        noCropToSell: 'You do not have this crop',
        sellCrops: 'E - Sell crops',
        gameTitle: 'Cabacos Farm',
        startGame: 'Start Game',
        saveGame: 'Save Game',
        loadGame: 'Load Game',
        saveComplete: 'Game saved',
        noSaves: 'No saves found',
        selectSlot: 'Select Slot',
        slot: 'Slot',
        emptySlot: 'Empty',
        settings: 'Settings',
        settingsTitle: 'Settings',
        pauseTitle: 'Game Paused',
        resume: 'Resume',
        language: 'Language',
        english: 'English',
        portuguese: 'Portuguese',
        korean: 'Korean',
        back: 'Back',
        gameOver: 'Game Over',
        inventoryTitle: 'Inventory',
        money: 'Money',
        energy: 'Energy',
        day: 'Day',
        seedShopTitle: 'Seed Shop',
        toolShopTitle: 'Tool Shop',
        farmPurchaseTitle: 'Farm Land',
        buy: 'Buy',
        owned: 'Owned',
        notEnoughMoney: 'Not enough money',
        inventoryFull: 'Inventory full',
        purchased: 'Purchased',
        landPurchased: 'Purchased',
        alreadyOwned: 'Already owned',
        itemAlreadyOwned: 'You already own this item',
        enterHouse: 'E - Enter house',
        enterMarket: 'E - Enter market',
        enterSeedShop: 'E - Enter shop',
        enterToolShop: 'E - Enter tool shop',
        enterTownHall: 'E - Enter town hall',
        exitBuilding: 'E - Exit',
        sleep: 'E - Sleep',
        buySeeds: 'E - Buy seeds',
        buyTools: 'E - Buy tools',
        fillWateringCan: 'E - Fill watering can',
        water: 'Water',
        buyFarms: 'E - Buy farm land',
        marketSellTab: 'Crops',
        marketQuestTab: 'Quests',
        activeQuests: 'Active Quests',
        questActive: 'Active Quest',
        questReady: 'Ready to claim',
        questProgress: 'Progress',
        reward: 'Reward',
        questActivate: 'Activate',
        questActivated: 'Quest activated',
        questAlreadyActive: 'Finish the active quest first',
        questClaim: 'Claim',
        questInProgress: 'In progress',
        questCompleted: 'Completed',
        questNotReady: 'Quest is not complete yet',
        questRewardClaimed: 'Quest completed',
        questPlantPumpkinsTitle: 'Plant Pumpkins',
        questPlantPumpkinsDescription: 'Plant 3 pumpkins on your farm.',
        questSellCarrotsTitle: 'Sell Carrots',
        questSellCarrotsDescription: 'Sell 3 carrots at the Crop Market.',
        questWaterPlantsTitle: 'Water Plants',
        questWaterPlantsDescription: 'Water any plants 10 times.',
        farm2Name: 'Farm 2',
        farm3Name: 'Farm 3',
        itemAxe: 'Axe',
        itemHoe: 'Hoe',
        itemRod: 'Fishing Rod',
        itemSickle: 'Sickle',
        itemShovel: 'Shovel',
        itemSword: 'Sword',
        itemWateringCan: 'Watering Can',
        seedBeetroot: 'Beetroot Seeds',
        seedCabbage: 'Cabbage Seeds',
        seedCarrot: 'Carrot Seeds',
        seedCauliflower: 'Cauliflower Seeds',
        seedKale: 'Kale Seeds',
        seedParsnip: 'Parsnip Seeds',
        seedPotato: 'Potato Seeds',
        seedPumpkin: 'Pumpkin Seeds',
        seedRadish: 'Radish Seeds',
        seedSunflower: 'Sunflower Seeds',
        seedWheat: 'Wheat Seeds',
        cropBeetroot: 'Beetroot',
        cropCabbage: 'Cabbage',
        cropCarrot: 'Carrot',
        cropCauliflower: 'Cauliflower',
        cropKale: 'Kale',
        cropParsnip: 'Parsnip',
        cropPotato: 'Potato',
        cropPumpkin: 'Pumpkin',
        cropRadish: 'Radish',
        cropSunflower: 'Sunflower',
        cropWheat: 'Wheat'
    },
    pt: {
        cropMarketTitle: 'Mercado de Colheitas',
        sell: 'Vender',
        sold: 'Vendeste',
        noCropToSell: 'Nao tens esta colheita',
        sellCrops: 'E - Vender colheitas',
        gameTitle: 'Quinta Cabacos',
        startGame: 'Começar Jogo',
        saveGame: 'Guardar Jogo',
        loadGame: 'Carregar Jogo',
        saveComplete: 'Jogo guardado',
        noSaves: 'Nao ha saves',
        selectSlot: 'Escolher Save',
        slot: 'Slot',
        emptySlot: 'Vazio',
        settings: 'Definições',
        settingsTitle: 'Definições',
        pauseTitle: 'Jogo em Pausa',
        resume: 'Continuar',
        language: 'Idioma',
        english: 'Inglês',
        portuguese: 'Português',
        korean: 'Coreano',
        back: 'Voltar',
        gameOver: 'Fim do Jogo',
        inventoryTitle: 'Inventário',
        money: 'Dinheiro',
        energy: 'Energia',
        day: 'Dia',
        seedShopTitle: 'Loja de Sementes',
        toolShopTitle: 'Loja de Ferramentas',
        farmPurchaseTitle: 'Terrenos da Quinta',
        buy: 'Comprar',
        owned: 'Comprado',
        notEnoughMoney: 'Dinheiro insuficiente',
        inventoryFull: 'Inventário cheio',
        purchased: 'Compraste',
        landPurchased: 'Compraste',
        alreadyOwned: 'Terreno ja comprado',
        itemAlreadyOwned: 'Ja tens este item',
        enterHouse: 'E - Entrar em casa',
        enterMarket: 'E - Entrar no mercado',
        enterSeedShop: 'E - Entrar na loja',
        enterToolShop: 'E - Entrar na loja de ferramentas',
        enterTownHall: 'E - Entrar na câmara',
        exitBuilding: 'E - Sair',
        sleep: 'E - Dormir',
        buySeeds: 'E - Comprar sementes',
        buyTools: 'E - Comprar ferramentas',
        fillWateringCan: 'E - Encher regador',
        water: 'Agua',
        buyFarms: 'E - Comprar terrenos',
        marketSellTab: 'Colheitas',
        marketQuestTab: 'Quests',
        activeQuests: 'Quests Ativas',
        questActive: 'Quest Ativa',
        questReady: 'Pronta para concluir',
        questProgress: 'Progresso',
        reward: 'Recompensa',
        questActivate: 'Ativar',
        questActivated: 'Quest ativada',
        questAlreadyActive: 'Termina primeiro a quest ativa',
        questClaim: 'Concluir',
        questInProgress: 'Em progresso',
        questCompleted: 'Concluida',
        questNotReady: 'A quest ainda nao esta completa',
        questRewardClaimed: 'Quest concluida',
        questPlantPumpkinsTitle: 'Plantar Aboboras',
        questPlantPumpkinsDescription: 'Planta 3 aboboras na tua quinta.',
        questSellCarrotsTitle: 'Vender Cenouras',
        questSellCarrotsDescription: 'Vende 3 cenouras no Mercado de Colheitas.',
        questWaterPlantsTitle: 'Regar Plantas',
        questWaterPlantsDescription: 'Rega qualquer tipo de planta 10 vezes.',
        farm2Name: 'Farm 2',
        farm3Name: 'Farm 3',
        itemAxe: 'Machado',
        itemHoe: 'Enxada',
        itemRod: 'Cana de Pesca',
        itemSickle: 'Foice',
        itemShovel: 'Pá',
        itemSword: 'Espada',
        itemWateringCan: 'Regador',
        seedBeetroot: 'Sementes de Beterraba',
        seedCabbage: 'Sementes de Couve',
        seedCarrot: 'Sementes de Cenoura',
        seedCauliflower: 'Sementes de Couve-flor',
        seedKale: 'Sementes de Couve-galega',
        seedParsnip: 'Sementes de Pastinaca',
        seedPotato: 'Sementes de Batata',
        seedPumpkin: 'Sementes de Abóbora',
        seedRadish: 'Sementes de Rabanete',
        seedSunflower: 'Sementes de Girassol',
        seedWheat: 'Sementes de Trigo',
        cropBeetroot: 'Beterraba',
        cropCabbage: 'Couve',
        cropCarrot: 'Cenoura',
        cropCauliflower: 'Couve-flor',
        cropKale: 'Couve-galega',
        cropParsnip: 'Pastinaca',
        cropPotato: 'Batata',
        cropPumpkin: 'Abóbora',
        cropRadish: 'Rabanete',
        cropSunflower: 'Girassol',
        cropWheat: 'Trigo'
    },
    ko: {
        cropMarketTitle: '작물 시장',
        sell: '판매',
        sold: '판매 완료',
        noCropToSell: '해당 작물이 없습니다',
        sellCrops: 'E - 작물 판매',
        gameTitle: '카바코스 농장',
        startGame: '게임 시작',
        saveGame: '게임 저장',
        loadGame: '불러오기',
        saveComplete: '저장되었습니다',
        noSaves: '저장 데이터가 없습니다',
        selectSlot: '슬롯 선택',
        slot: '슬롯',
        emptySlot: '비어있음',
        settings: '설정',
        settingsTitle: '설정',
        pauseTitle: '일시 정지',
        resume: '계속하기',
        language: '언어',
        english: '영어',
        portuguese: '포르투갈어',
        korean: '한국어',
        back: '뒤로',
        gameOver: '게임 오버',
        inventoryTitle: '인벤토리',
        money: '돈',
        energy: '에너지',
        day: '일차',
        seedShopTitle: '씨앗 상점',
        toolShopTitle: '도구 상점',
        farmPurchaseTitle: '농장 땅',
        buy: '구매',
        owned: '보유 중',
        notEnoughMoney: '돈이 부족합니다',
        inventoryFull: '인벤토리가 가득 찼습니다',
        purchased: '구매 완료',
        landPurchased: '구매 완료',
        alreadyOwned: '이미 보유한 땅입니다',
        itemAlreadyOwned: '이미 보유한 아이템입니다',
        enterHouse: 'E - 집 들어가기',
        enterMarket: 'E - 시장 들어가기',
        enterSeedShop: 'E - 상점 들어가기',
        enterToolShop: 'E - 도구 상점 들어가기',
        enterTownHall: 'E - 시청 들어가기',
        exitBuilding: 'E - 나가기',
        sleep: 'E - 잠자기',
        buySeeds: 'E - 씨앗 구매',
        buyTools: 'E - 도구 구매',
        fillWateringCan: 'E - 물 주머니 채우기',
        water: '물',
        buyFarms: 'E - 농장 땅 구매',
        marketSellTab: '작물',
        marketQuestTab: '퀘스트',
        activeQuests: '진행 중인 퀘스트',
        questActive: '진행 중',
        questReady: '완료 - 보상 받기',
        questProgress: '진행도',
        reward: '보상',
        questActivate: '수락',
        questActivated: '퀘스트가 수락되었습니다',
        questAlreadyActive: '먼저 진행 중인 퀘스트를 완료하세요',
        questClaim: '보상 받기',
        questInProgress: '진행 중',
        questCompleted: '완료',
        questNotReady: '퀘스트가 아직 완료되지 않았습니다',
        questRewardClaimed: '퀘스트 완료',
        questPlantPumpkinsTitle: '호박 심기',
        questPlantPumpkinsDescription: '농장에 호박 3그루를 심으세요.',
        questSellCarrotsTitle: '당근 판매',
        questSellCarrotsDescription: '작물 시장에서 당근 3개를 판매하세요.',
        questWaterPlantsTitle: '식물에 물주기',
        questWaterPlantsDescription: '아무 식물이나 10번 물을 주세요.',
        farm2Name: '농장 2',
        farm3Name: '농장 3',
        itemAxe: '도끼',
        itemHoe: '괭이',
        itemRod: '낚싯대',
        itemSickle: '낫',
        itemShovel: '삽',
        itemSword: '검',
        itemWateringCan: '물 주전자',
        seedBeetroot: '비트 씨앗',
        seedCabbage: '양배추 씨앗',
        seedCarrot: '당근 씨앗',
        seedCauliflower: '콜리플라워 씨앗',
        seedKale: '케일 씨앗',
        seedParsnip: '파스닙 씨앗',
        seedPotato: '감자 씨앗',
        seedPumpkin: '호박 씨앗',
        seedRadish: '무 씨앗',
        seedSunflower: '해바라기 씨앗',
        seedWheat: '밀 씨앗',
        cropBeetroot: '비트',
        cropCabbage: '양배추',
        cropCarrot: '당근',
        cropCauliflower: '콜리플라워',
        cropKale: '케일',
        cropParsnip: '파스닙',
        cropPotato: '감자',
        cropPumpkin: '호박',
        cropRadish: '무',
        cropSunflower: '해바라기',
        cropWheat: '밀'
    }
};

export type TranslationKey = keyof typeof translations.en;

export function getCurrentLanguage(): GameLanguage {
    const savedLanguage = localStorage.getItem(languageStorageKey);

    if (isGameLanguage(savedLanguage)) {
        return savedLanguage;
    }

    return defaultLanguage;
}

export function setCurrentLanguage(language: GameLanguage): void {
    localStorage.setItem(languageStorageKey, language);
}

export function translate(key: TranslationKey): string {
    return translations[getCurrentLanguage()][key];
}

export function getAvailableLanguages(): GameLanguage[] {
    return ['ko', 'pt', 'en'];
}

export function getLanguageLabel(language: GameLanguage): string {
    if (language === 'ko') return translate('korean');
    if (language === 'pt') return translate('portuguese');
    return translate('english');
}

function isGameLanguage(value: string | null): value is GameLanguage {
    return value === 'en' || value === 'pt' || value === 'ko';
}
